export enum CoffeActionTypes {
    COFFEE_FETCHING_STARTED = 'COFFEE_FETCHING_STARTED',
    COFFEE_FETCHING_SUCCEEDED = 'COFFEE_FETCHING_SUCCEEDED',
    COFFEE_FETCHING_FAILED = 'COFFEE_FETCHING_FAILED',
}
